<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Promise</title>
</head>
<body>
    
</body>
<script>
   const promiseOne = new Promise( function(resolve, reject){
    // Do any async task
    // DB calls, cryptography, network
    setTimeout(function (){
        console.log('Async task is completed');
       resolve();
    },1000)
   });
     promiseOne.then(function(){
        console.log('Promise completed');
     });

     const promiseTwo = new Promise( function(resolve, reject){
         setTimeout(function(){
          resolve({username: "Aisha", email: "aisha@gmail.com"});

         },1000)
        
     })
     promiseTwo.then(function (user) {
       console.log(user);
         })

        //  Chaining Promises
        const promiseThree = new Promise(function(resolve, reject){
            setTimeout(function(){
                let error = false
               
                  if(!error){
                    resolve({username:'Amreen',emailId:'amreen@gmail.com'});
                  }
                  else{
                    reject('Error: something went wrong')
                  }
            },1000)
        })
        promiseThree.then((user)=>{
           console.log(user);
           return user.username;
        }).then((username) => {
            console.log(username);
        }).catch((error)=>{
            console.log(error);
        }).finally(()=> {
            console.log("The promise is either resolve or rejected");
        })
    
    // Promise Four with try catch 
   const promiseFour = new Promise(function(resolve,reject){
       setTimeout(function(){
        let error = true;
        if(!error){
            resolve({username:'js',password:123})
        }
        else{
            reject("ERROR: Something Went Wrong");
        }
       },1000)
   });
   async function consumePromiseFour(){
    try {
        const response = await promiseFour
        console.log(response); 
    }
    catch (error){
        console.log(error);
    }
   }
   consumePromiseFour();


//   promise to call API with try catch
// async function getAllUsers(){
//     try{
//         const response = await fetch('https://jsonplaceholder.typicode.com/users')
//     const data = await response.json();
//     console.log(data);
//     }
//     catch (error){
//         console.log(error);
//     }
// } 
// getAllUsers()


fetch("https://api.github.com/users/hiteshchoudhary")
.then((response) => {
    return response.json()
})
.then((data) => {
    console.log(data);
})
.catch((error) => console.log(error))
</script>
</html>